version: "3.7"

services:  
  nginx_sqlsrv:
    image: nginx:stable-alpine
    container_name: nginx_sqlsrv
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_sqlsrv
      - mysql
    networks:
      - networkapp

  mysql_sqlsrv:
    image: mysql:5.7
    container_name: mysql_sqlsrv
    restart: always
    environment:
      MYSQL_DATABASE: db_sqlsrv
      MYSQL_USER: usr_container
      MYSQL_PASSWORD: pss_container
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - 33069:3306
    volumes:
      - _vol:/var/lib/mysql
    networks:
      - networkapp

  app_sqlsrv:
    image: php_7_4_sqlsrv
    container_name: app_sqlsrv
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp
    ports:
      - 8448:80

networks: 
  networkapp:

volumes:
  _vol:
